db:
  host: 'database' # This is the name of the service (see docker-compose.yml from pictalk-frontend) that runs the database
  username: 'postgres'
  password: 'postgres'
  synchronize: true

jwt: 
  secret: 'WayTooMuchSunScreen'
